config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get 'palettes/search' => 'palettes#search'

  get 'colors/search' => 'colors#search'

  resources :colors

  resources :palettes
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.per_page = 8

  def downcase_name
    self.name = name.downcase
  end
end

app/models/color.rb
# frozen_string_literal: true

class Color < ApplicationRecord
  has_many :palette_colors
  has_many :palettes, through: :palette_colors
  before_save :downcase_name

  validates :name,
            presence: true,
            length: { in: 3..25 },
            uniqueness: { case_sensitive: false }
  validates :hex_code,
            presence: true,
            uniqueness: true
end

app/models/palette.rb
# frozen_string_literal: true

class Palette < ApplicationRecord
  belongs_to :user
  has_many :palette_colors
  has_many :colors, through: :palette_colors
  accepts_nested_attributes_for :palette_colors

  before_save :downcase_name

  after_save do
    UserPaletteMailer.palette_creation_email(user).deliver_later
  end

  after_destroy do
    UserPaletteMailer.palette_deletion_email(user).deliver_later
  end

  validates :name,
            presence: true,
            length: { in: 3..25 },
            uniqueness: { case_sensitive: false }
end

app/models/palette_color.rb
# frozen_string_literal: true

class PaletteColor < ApplicationRecord
  belongs_to :color
  belongs_to :palette
  validates :color_id,
            presence: true,
            uniqueness: { scope: :palette_id,
                          message: 'Pallete must have unique colors' }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :palettes

  validate :valid_image_type

  has_one_attached :avatar

  private

  def valid_image_type
    return unless avatar.attached? && !avatar.content_type
                                             .in?(%w[image/jpeg image/png])

    errors.add(:avatar, 'Only JPEG and PNG formats are allowed.!')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer
      .permit(:account_update, keys: %i[email
                                        password
                                        password_confirmation
                                        current_password
                                        avatar])
  end
end

app/controllers/colors_controller.rb
# frozen_string_literal: true

class ColorsController < ApplicationController
  before_action :current_color, only: %i[show edit update destroy]
  before_action :authenticate_user!


  def index
    @colors = Color.paginate(page: params[:page])
  end

  def show; end

  def new
    @color = Color.new
  end

  def edit; end

  def create
    @color = Color.new(color_params)
    if @color.save
      flash[:success] = 'Color created successfully'
      redirect_to colors_path
    else
      render :new
    end
  end

  def update
    if @color.update(color_params)
      flash[:success] = 'Color details updated successfully'
      redirect_to colors_path
    else
      render :edit
    end
  end

  def destroy
    if @color.destroy
      flash[:success] = 'Color deleted successfully'
      redirect_to colors_path
    else
      flash.now[:danger] = @color.errors.full_messages.join('<br>').html_safe
      render :index
    end
  end

  def search
    @colors = Color.all
                   .where('name like ?', "%#{params[:keyword]}%")
                   .paginate(page: params[:page])
  end

  private

  def color_params
    params.require(:color).permit(:name, :hex_code)
  end

  def current_color
    @color = Color.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/palettes_controller.rb
# frozen_string_literal: true

class PalettesController < ApplicationController
  before_action :current_palette, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @palettes = current_user.palettes.paginate(page: params[:page])
  end

  def show; end

  def new
    @palette = current_user.palettes.new
  end

  def edit; end

  def create
    @palette = current_user.palettes.new(palette_params)
    if @palette.save
      flash[:success] = 'Your palette has been created successfully.'
      redirect_to palettes_path
    else
      render :new
    end
  end

  def update
    if @palette.update(palette_params)
      flash[:success] = 'Palette details updated successfully'
      redirect_to palettes_path
    else
      render :edit
    end
  end

  def destroy
    if @palette.destroy
      flash[:success] = 'Palette deleted successfully'
      redirect_to palettes_path
    else
      flash.now[:danger] = @palette.errors.full_messages.join('<br>').html_safe
      render :index
    end
  end

  def search
    @palettes = current_user.palettes
                            .where('name like ?', "%#{params[:keyword]}%")
                            .paginate(page: params[:page])
  end

  private

  def palette_params
    params.require(:palette).permit(
      :name,
      palette_colors_attributes: %i[id pallete_id color_id _destroy]
    )
  end

  def current_palette
    @palette = current_user.palettes.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/colors/_color_actions.html.erb
<p><%= link_to "Edit color", edit_color_path(color), class: "btn btn-primary btn-xs" %> <%= link_to "Delete color", color_path(color), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Sure to delete color permanently?" } %></p>

app/views/colors/_colors_listing.html.erb
<% if @colors.present? %>
  <div class="row">
  <% @colors.order("updated_at DESC").each do |color| %>
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <%= link_to color_path(color) do %>
          <div style="background-color: <%= color.hex_code %>; height: 150px"></div>
        <% end %>
        <div class="caption">
          <strong><%= color.name.capitalize %></strong>
          <p>[ <%= link_to color.hex_code, color_path(color) %> ]</p>
          <%= render 'color_actions', color: color %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="row">
    <%= will_paginate @colors, renderer: BootstrapPagination::Rails %>
  </div>
<% else %>
  <h1>No search result found :(</h1>
<% end %>

app/views/colors/_form.html.erb
<%= render 'common/errors', resource: @color %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@color, :html => { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of color", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :color %>
        </div>
        <div class="col-sm-8">
          <%= f.color_field :hex_code, id: "color-input" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<p align="center">
  [ <%= link_to "Cancel request and goto available colors", colors_path %> ]
</p>

app/views/colors/edit.html.erb
<h1 align="center">Edit Color</h1>

<%= render 'common/errors', resource: @color %>

<%= render 'form' %>

app/views/colors/index.html.erb
<h1 align="center">Colors</h1>
<div class="row">
  <div class="col-md-3">
    <% if user_signed_in? %>
      <%= link_to "Add new color", new_color_path, class: "btn btn-md btn-primary" %>
    <% end %>
  </div>
  <div class="col-md-6">
    <form align="center">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search color" id="search-color" >
      </div>
    </form>
  </div>
</div>
<div class="row">
  <div id="color-section">
    <%= render partial: 'colors_listing' %>
  </div>
</div>

<script>
  $(document).on('keyup', '#search-color', function(){
    var keyword = $(this).val();
    $.ajax({
      method: 'GET',
      url: 'colors/search',
      data: { keyword: keyword }
    });
  });
</script>

app/views/colors/new.html.erb
<h1 align="center">Create Color</h1>

<%= render 'form' %>

app/views/colors/search.js.erb
$("#color-section").html("<%= j(render(partial: 'colors_listing')) %>");

app/views/colors/show.html.erb
<h1><%= @color.name.capitalize %></h1>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div style="background-color: <%= @color.hex_code %>; height: 250px">
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <h3><%= @color.hex_code %></h3>
    <%= render 'color_actions', color: @color %>
  </div>
</div>

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <strong>
              <%= pluralize(resource.errors.count, 'error') %>
            prohibited this article from being saved
            </strong>
          </h2>
          <div class="panel-body">
            <ul>
              <% resource.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>    
          </div>
        </div>
      </div>
    </div>    
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>   
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ColorPalette", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Palettes", palettes_path %></li>
        <li><%= link_to "Colors", colors_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Palette", new_palette_path %></li>
            <li><%= link_to "Color", new_color_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %>&nbsp;<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit profile", edit_user_registration_path(current_user) %></li>
              <li><a href="#">Your Palettes</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorPalette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron center">
	<div class="jb-content">
		<h1>Color palette!</h1>
  <p></p>
  <p><%= link_to('Sign up for ColorPalette', new_user_registration_path , class: "btn btn-primary btn-lg") unless user_signed_in? %></p>
	</div>
</div>

app/views/palettes/_form.html.erb
<%= render 'common/errors', resource: @palette %>

<div class="row">
  <div class="col-xs-12">
    <%= nested_form_for @palette, :html => { class: "form-horizontal", role: "form" } do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :palette_name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of color", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :add_colors %>
        </div>
        <div class="col-sm-8">
          <%= f.fields_for :palette_colors do |color_palette| %>
            <%= color_palette.select(
                                    :color_id,
                                    options_from_collection_for_select(Color.all,
                                                                      :id,
                                                                      :name,
                                                                      color_palette.object.color_id),
                                    {},
                                    { :class => 'form-control col-sm-6' }) %>
            <%= color_palette.link_to_remove "Remove" %>
          <% end %>
          <%= f.link_to_add "Add a color", :palette_colors, class: "btn btn-sm btn-success" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<p align="center">
  [ <%= link_to "Cancel request and goto available palettes", palettes_path %> ]
</p>

app/views/palettes/_palette_actions.html.erb
<p><%= link_to "Edit palette", edit_palette_path(palette), class: "btn btn-primary btn-xs" %> <%= link_to "Delete palette", palette_path(palette), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Sure to delete palette permanently?" } %></p>

app/views/palettes/_palettes_listing.html.erb
<% if @palettes.present? %>
  <div class="row">
  <table class="table">
    <tr>
      <th>Palette name</th>
      <th>Swatches</th>
      <th>Actions</th>
    </tr>
    <% @palettes.order("updated_at DESC").each do |palette| %>
    <tr>
      <td><%= link_to palette.name.capitalize, palette_path(palette) %></td>
      <td>
        <% palette.colors.each do |color| %>
          <%= link_to color_path(color) do %>
            <div id="swatch-color-div" style="background-color: <%= color.hex_code %>;"></div>
          <% end %>
        <% end %>
      </td>
      <td><%= render 'palette_actions', palette: palette %></td>
    </tr>
    <% end %>
  </table>
</div>
  <div class="row">
    <%= will_paginate @palettes, renderer: BootstrapPagination::Rails %>
  </div>
<% else %>
  <h1>No search results found :(</h1>
<% end %>

app/views/palettes/edit.html.erb
<h1 align="center">Update Palette</h1>

<%= render 'form' %>

app/views/palettes/index.html.erb
<h1 align="center">Palettes</h1>
<p id="msg"></p>
<div class="row">
  <div class="col-md-3">
    <% if user_signed_in? %>
    <%= link_to "Add new palette", new_palette_path, class: "btn btn-md btn-primary" %>
    <% end %>
  </div>
  <div class="col-md-6">
    <form align="center">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search palette" id="search-palette" >
      </div>
    </form>
  </div>
</div>
<div class="row">
  <div id='palette-section'>
    <%= render partial: 'palettes_listing'%>
  </div>  
</div>

<script>
  $(document).on('keyup', '#search-palette', function (){
    var keyword = $(this).val();
    $.ajax({
      method: "GET",
      url: "palettes/search",
      data: { keyword: keyword }
    });
  });
</script>  

app/views/palettes/new.html.erb
<h1 align="center">Create Palette</h1>

<%= render 'form' %>

app/views/palettes/search.js.erb
$("#palette-section").html("<%= j(render(partial: 'palettes_listing')) %>");

app/views/palettes/show.html.erb
<h1><%= @palette.name.capitalize %></h1>

<div class="row">
  <div class="col-xs-6 col-md-4">
    <div class="thumbnail">
      <% @palette.colors.each do |color| %>
        <div style="background-color: <%= color.hex_code %>; height: 50px;"></div>
      <% end %>
    </div>
  </div>
  <div class="col-xs-6 col-md-4">
    <div class="caption">
      <strong>Colors</strong>
      <% @palette.colors.each do |color| %>
        <li><%= link_to color.name.capitalize, color_path(color) %></li>
      <% end %><br>
      <%= render 'palette_actions', palette: @palette %>
    </div>
  </div>
</div>

app/views/users/login.html.erb
<h1>Login</h1>

<%= form_for(@user, {url: ''}) do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit "Login" %>
  </p>
<% end %>

<p>New user? <%= link_to 'Sign up', signup_path %></p>